name: Tinify for Mac feature request
description: Suggest an improvement to the Mac app.
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Suggested behavior
    validations:
      required: true
